### ISSUE TITLE
SPDX SBOM Generator Bug Report

### ISSUE THREAD

**Issue by planetf1** [opensbom-generator/spdx-sbom-generator#246]
## Summary

Unclear how to install cleanly

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

Tried two ways: (on MacOS 12.5 Beta currently)

* Used homebrew on macos `brew install spdx-sbom-generator'
* Downloaded latest version of spdx-sbom-generator (after removing above) [Useful if there was a '--version' CLI option]

## Expected behavior

Use tool to start scanning my files

## Screenshots

I am in the top level of my source tree, and run the command:
```
master git:(master) spdx-sbom-generator
INFO[2022-06-13T13:22:07+01:00] Starting to generate SPDX ...                
FATA[2022-06-13T13:22:07+01:00] Failed to initialize command: * Please install dependencies by running the following command :
	1) bundle config set --local path 'vendor/bundle' && bundle install && bundle exec rake install
	2) run the spdx-sbom-generator tool command 
➜  master git:(master) type spdx-sbom-generator                                         
spdx-sbom-generator is /Users/jonesn/bin/spdx-sbom-generator
➜  master git:(master) bundle config set --local path 'vendor/bundle' && bundle install && bundle exec rake install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Following files may not be writable, so sudo is needed:
  /Library/Ruby/Gems/2.6.0
  /Library/Ruby/Gems/2.6.0/build_info
  /Library/Ruby/Gems/2.6.0/cache
  /Library/Ruby/Gems/2.6.0/doc
  /Library/Ruby/Gems/2.6.0/extensions
  /Library/Ruby/Gems/2.6.0/gems
  /Library/Ruby/Gems/2.6.0/specifications
Fetching concurrent-ruby 1.1.10


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
sudo: a password is required
```

It's not clear what the tool is doing at this point - I couldn't see any reference on the README. Using homebrew, much of the tools are installed via this package manager, so I am careful not to allow overwrites.

I would have expected clarification in the docs, or it could be that there is something wrong?

## Repository

https://github.com/odpi/egeria

 - though at this point scanning hasn't started
 
## Additional Context

n/a

## Acceptance Criteria

Progress to next step of scanning code

## References

**Update**

I then decided to allow the ruby module updates, having checked what I had in this local directory (not wanting overwrites) only to get:

```
➜  master git:(master) bundle config set --local path 'vendor/bundle' && bundle install && bundle exec rake install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Following files may not be writable, so sudo is needed:
  /Library/Ruby/Gems/2.6.0
  /Library/Ruby/Gems/2.6.0/build_info
  /Library/Ruby/Gems/2.6.0/cache
  /Library/Ruby/Gems/2.6.0/doc
  /Library/Ruby/Gems/2.6.0/extensions
  /Library/Ruby/Gems/2.6.0/gems
  /Library/Ruby/Gems/2.6.0/specifications
Fetching concurrent-ruby 1.1.10


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Installing concurrent-ruby 1.1.10
Fetching i18n 0.9.5
Installing i18n 0.9.5
Fetching minitest 5.15.0
Installing minitest 5.15.0
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.9
Installing tzinfo 1.2.9
Fetching zeitwerk 2.5.4
Installing zeitwerk 2.5.4
Fetching activesupport 6.0.5
Installing activesupport 6.0.5
Fetching public_suffix 4.0.7
Installing public_suffix 4.0.7
Fetching addressable 2.8.0
Installing addressable 2.8.0
Using bundler 1.17.2
Fetching coffee-script-source 1.11.1
Installing coffee-script-source 1.11.1
Fetching execjs 2.8.1
Installing execjs 2.8.1
Fetching coffee-script 2.4.1
Installing coffee-script 2.4.1
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching commonmarker 0.23.5
Installing commonmarker 0.23.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/private/var/folders/r4/__255k7j04b669bbthwrk9340000gn/T/bundler20220613-81709-iaijkxcommonmarker-0.23.5/gems/commonmarker-0.23.5/ext/commonmarker
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220613-81709-9cj8wb.rb
extconf.rb
mkmf.rb can't find header files for ruby at
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in
/var/folders/r4/__255k7j04b669bbthwrk9340000gn/T/bundler20220613-81709-iaijkxcommonmarker-0.23.5/gems/commonmarker-0.23.5
for inspection.
Results logged to
/var/folders/r4/__255k7j04b669bbthwrk9340000gn/T/bundler20220613-81709-iaijkxcommonmarker-0.23.5/extensions/universal-darwin-21/2.6.0/commonmarker-0.23.5/gem_make.out

An error occurred while installing commonmarker (0.23.5), and Bundler cannot continue.
Make sure that `gem install commonmarker -v '0.23.5' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github-pages was resolved to 226, which depends on
    jekyll-commonmark-ghpages was resolved to 0.2.0, which depends on
      jekyll-commonmark was resolved to 1.4.0, which depends on
        commonmarker
``` 

This looks like typical package version dependency issues - perhaps as a standalone tool we need to use a 'local context' of some kind. Not knowing ruby, perhaps this should be in the documentation?       

Ah
```
You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.
```

I think as the tool is intended for go, java developers etc, some elaboration around getting the dependencies right to be able to run it would be really useful?

**Comment by planetf1** [comment]
Tried the same on linux:

```
➜  master git:(master) spdx-sbom-generator
INFO[2022-06-13T12:53:12Z] Starting to generate SPDX ...                
FATA[2022-06-13T12:53:12Z] Failed to initialize command: * Please install dependencies by running the following command :
	1) bundle config set --local path 'vendor/bundle' && bundle install && bundle exec rake install
	2) run the spdx-sbom-generator tool command 
➜  master git:(master) ✗ bundle config set --local path 'vendor/bundle' && bundle install && bundle exec rake install
Command 'bundle' not found, but can be installed with:
sudo snap install ruby          # version 3.1.2, or
sudo apt  install ruby-bundler  # version 2.3.5-2
See 'snap info ruby' for additional versions.
```

which is clear - dependent software is needed

I instead did 
```
sudo apt install ruby ruby-bundler
```
to get a local install, and then repeated the bundle config command

This again failed with dependency issues, despite this being a new, clean install on Linux (ubuntu 22.04)

The error included (full log very long)
```
Installing activesupport 6.0.5
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
I then tried
```
apt install ruby-dev
```
This worked a lot better but ended up with
```
Post-install message from html-pipeline:
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
/usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/rubygems_integration.rb:331:in `block in replace_bin_path': can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /usr/share/rubygems-integration/all/gems/bundler-2.3.5/lib/bundler/rubygems_integration.rb:359:in `block in replace_bin_path'
	from /usr/bin/rake:25:in `<main>
```
