### ISSUE TITLE
Did not generate a SPDX-file

### ISSUE THREAD

**Issue by Padina14** [opensbom-generator/spdx-sbom-generator#296]
## Summary

I started  spdx-sbom-generator (current version), to generate an SBOM.
I can't detext the current version with `spdx-sbom-generator --version` (command not defined yet).
I got the output in the console:
```
INFO[2023-08-07T11:25:26+02:00] Starting to generate SPDX ...                
INFO[2023-08-07T11:25:26+02:00] Running generator for Module Manager: `composer` with output `bom-composer.spdx` 
INFO[2023-08-07T11:25:26+02:00] Running generator for Module Manager: `npm` with output `bom-npm.spdx` 
INFO[2023-08-07T11:25:27+02:00] Current Language Version 9.6.4               
INFO[2023-08-07T11:25:27+02:00] Global Setting File                          
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/spdx/spdx-sbom-generator/pkg/modules/npm.getPackageDependencies(0x17d443f?, {0x17dcc4a, 0xc})
	/private/tmp/spdx-sbom-generator-20221123-4665-z9g2li/spdx-sbom-generator-0.0.15/pkg/modules/npm/handler.go:317 +0x4d8
github.com/spdx/spdx-sbom-generator/pkg/modules/npm.(*npm).buildDependencies(0xc00008a1e0, {0x17d43ec, 0x1}, 0x8?)
	/private/tmp/spdx-sbom-generator-20221123-4665-z9g2li/spdx-sbom-generator-0.0.15/pkg/modules/npm/handler.go:203 +0x2b0
github.com/spdx/spdx-sbom-generator/pkg/modules/npm.(*npm).ListModulesWithDeps(0xc00008a1e0?, {0x17d43ec, 0x1}, {0x16?, 0xc0032df9b0?})
	/private/tmp/spdx-sbom-generator-20221123-4665-z9g2li/spdx-sbom-generator-0.0.15/pkg/modules/npm/handler.go:185 +0x1ae
github.com/spdx/spdx-sbom-generator/pkg/modules.(*Manager).Run(0xc00008a320)
	/private/tmp/spdx-sbom-generator-20221123-4665-z9g2li/spdx-sbom-generator-0.0.15/pkg/modules/modules.go:102 +0x15a
github.com/spdx/spdx-sbom-generator/pkg/handler.(*spdxHandler).Run(0xc0000d41c0)
	/private/tmp/spdx-sbom-generator-20221123-4665-z9g2li/spdx-sbom-generator-0.0.15/pkg/handler/spdx.go:88 +0x309
main.generate(0x1fc1540, {0x17d5311?, 0x1?, 0x1?})
	/private/tmp/spdx-sbom-generator-20221123-4665-z9g2li/spdx-sbom-generator-0.0.15/cmd/generator/generator.go:121 +0x372
github.com/spf13/cobra.(*Command).execute(0x1fc1540, {0xc000024050, 0x1, 0x1})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1fc1540)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/private/tmp/spdx-sbom-generator-20221123-4665-z9g2li/spdx-sbom-generator-0.0.15/cmd/generator/generator.go:39 +0x65


```
No file was generated.

## Background

Mac - Ventura 13.5(current)

## Expected behavior

The programm generate one ore more text-files in SPDX-format.

**Comment by nishakm** [comment]
Hi @Padina14, this project is currently under reconstruction. We will address this issue once it is done.

**Comment by ghost** [comment]
> Hi @Padina14, this project is currently under reconstruction. We will address this issue once it is done.

I also faced this issue.
Ubuntu - WSL
![Screenshot 2024-12-30 114103](https://github.com/user-attachments/assets/a047f219-6bcd-42c7-8332-c29e250d744d)
Windows 11
![Screenshot 2024-12-30 114014](https://github.com/user-attachments/assets/012d3412-564c-42c5-9a7d-9bc08e76b71f)
